config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  
  
  resources :users do
    resources :saves
    resources :presales
    resources :bans
  end
  resources :events  do
      resources :evaluations

      
  end
  root to: 'events#index'
  post "/events", to: "events#create",as: "create_event"
  delete "/users/:user_id/:event_id/saves", to: "saves#destroy",as: "delete_saves"
  post "/events/:event" ,to: "events#create",as: "draft_event"
  post "events/:event_id/create_order", to: "presales#create_order",as: "create_order"
  get "events/:event_id/presales/capture_order", to: "presales#capture_order"
  get "events/:event_id/presales/cancel_order", to: "presales#cancel_order"
  get "events/:event_id/presales",to: "presales#index",as: "all_presales"
  get "events/:role",to: "events#index",as: "index_events"
  get "users/:user_id/create_order",to: "users#create_order",as: "premium"
  get "users/:user_id/capture_order",to: "users#capture_order"
  get "users/:user_id/cancel_order",to: "users#cancel_order"
  get "users/:user_id/geolocation", to: "users#geolocation"
  post "/users/save_coordinates", to: "users#save_coordinates"

  post "/events/:event_id/evaluations/:star_radio", to: "evaluations#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :event_id,:user_id,:value,presence:true
  validates_uniqueness_of :event_id, scope: :user_id
  validates :value, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }, unless: -> { :value.nil? }
  validate :print_errors
  after_destroy :update_avgvalue

  def update_avgvalue
    event.update_attribute(:avgvalue,Evaluation.where(event_id: event.id).average(:value))
    if event.avgvalue == nil 
      event.update_attribute(:avgvalue,0.0)
    end

  end
  def print_errors
    errors.full_messages.each do |message|
        puts message
  end
end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @evaluation=Evaluation.new
  end

  def create
    value=params[:star_radio]
    puts value
    @evaluation=Evaluation.new(event_id: params[:event_id],user_id: current_user.id,value: value)
       
    if @evaluation.save
      event=Event.find(params[:event_id])
      event.update_attribute(:avgvalue,Evaluation.where(event_id: event.id).average(:value))
      flash[:success]="L\'evento è stato valutato correttamente"
      respond_to do |format|
        format.json { render json: { message: "Evento valutato correttamente"},redirect_url: events_path, status: :created }
      end
    else
      flash[:error] = @evaluation.errors.full_messages.join(', ')
      respond_to do |format|
        format.json {render json: { error: "Errore nella valutazione dell'evento" },redirect_url: event_path(id: params[:event_id],commit: "presale"), status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/create.html.erb
<h1>Evaluations#create</h1>
<p>Find me in app/views/evaluations/create.html.erb</p>

app/views/evaluations/destroy.html.erb
<h1>Evaluations#destroy</h1>
<p>Find me in app/views/evaluations/destroy.html.erb</p>

app/views/evaluations/edit.html.erb
<h1>Evaluations#edit</h1>
<p>Find me in app/views/evaluations/edit.html.erb</p>

app/views/evaluations/index.html.erb
<h1>Evaluations#index</h1>
<p>Find me in app/views/evaluations/index.html.erb</p>

app/views/evaluations/new.html.erb
<h1>Evaluations#new</h1>
<%= form_for @evaluation,url: event_evaluations_path(event_id: params[:event_id]),method: :post do |form| %>
  <div class="form-group">
    <%= form.label :value, 'Valutazione (da 1 a 10)' %>
    <%= form.number_field :value, in: 1..10, class: 'form-control', required: true %>
  </div>
  <%= form.submit 'Invia', class: 'btn btn-primary' %>
<%= link_to "Annulla", event_path(id: params[:event_id]) %>
<% end %>

app/views/evaluations/show.html.erb
<h1>Evaluations#show</h1>
<p>Find me in app/views/evaluations/show.html.erb</p>

app/views/evaluations/update.html.erb
<h1>Evaluations#update</h1>
<p>Find me in app/views/evaluations/update.html.erb</p>