config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  
  
  resources :users do
    resources :saves
    resources :presales
    resources :bans
  end
  resources :events  do
      resources :evaluations

      
  end
  root to: 'events#index'
  post "/events", to: "events#create",as: "create_event"
  delete "/users/:user_id/:event_id/saves", to: "saves#destroy",as: "delete_saves"
  post "/events/:event" ,to: "events#create",as: "draft_event"
  post "events/:event_id/create_order", to: "presales#create_order",as: "create_order"
  get "events/:event_id/presales/capture_order", to: "presales#capture_order"
  get "events/:event_id/presales/cancel_order", to: "presales#cancel_order"
  get "events/:event_id/presales",to: "presales#index",as: "all_presales"
  get "events/:role",to: "events#index",as: "index_events"
  get "users/:user_id/create_order",to: "users#create_order",as: "premium"
  get "users/:user_id/capture_order",to: "users#capture_order"
  get "users/:user_id/cancel_order",to: "users#cancel_order"
  get "users/:user_id/geolocation", to: "users#geolocation"
  post "/users/save_coordinates", to: "users#save_coordinates"

  post "/events/:event_id/evaluations/:star_radio", to: "evaluations#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :ban, optional:true ,dependent: :destroy
  has_many :saves,dependent: :destroy,class_name: "Save"
  has_many :presales,dependent: :destroy
  has_many :evaluations,dependent: :destroy
  has_many :events,dependent: :destroy,foreign_key: 'organizer_id'
  has_many :bans,dependent: :destroy
  has_many :presale_events, through: :presales, :source => :event
  has_many :saved_events, through: :saves, :source => :event
  has_many :evaluated_events, through: :evaluations, :source => :event
  validate :print_errors
  validates :username,presence:true,uniqueness:true #non voglio avere utenti con lo stesso nome 

  validates :role, inclusion: { in: %w[user organizer admin] }
   
  
  def print_errors
      errors.full_messages.each do |message|
          puts message
    end
  end
  def banned?
    Ban.where(user_id: id).exists?
  end
       

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role,:username])
  end
  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:role,:username])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  #DELETE /resource/sign_out
  #def destroy
    #super
    #redirect_to root_path
  #end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
require 'net/http'
class UsersController < ApplicationController
  before_action :authenticate_user!
 
  def index
    @event = Event.find(params[:id])
    @users = User.joins(:presales).where(presales: { event_id: @event.id }).uniq
    @presales= Presale.where(event_id: @event.id)
  end

  def geolocation
    url = URI.parse('https://ip-geo-location.p.rapidapi.com/ip/check')
    headers = {
      'X-RapidAPI-Key' => '9917380005mshdb6755bf2e2e54ap158693jsndca67ed43af4',
      'X-RapidAPI-Host' => 'ip-geo-location.p.rapidapi.com'
   }
parameters = {
  'format' => 'json',
	'filter' => 'city'
}
# Esegui la richiesta POST per ottenere l'access token
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
request = Net::HTTP::Post.new(url.path+"?"+ URI.encode_www_form(parameters), headers)
response = http.request(request)
puts response.body

end

  def show
    @is_event_background=true
    @user = User.find(params[:id])
  end
  

  def new
  end

  def create
  end

  def edit
    if params[:commit]=="Revoca"
      @user=User.find(params[:id])
      if @user.update(role: "user" )
        flash[:success]="L\'organizzatore ora è un utente"
      else
        flash[:error]="Non è possibile effettuare questa operazione."
      end
      redirect_to user_path(id: params[:id])
    end

      
  end

  def update
  end
  def create_order
    url = URI.parse('https://api-m.sandbox.paypal.com/v1/oauth2/token')
    headers = {
  'Content-Type' => 'application/x-www-form-urlencoded',
  'Authorization' => 'Basic ' + Base64.strict_encode64("#{ENV['PAYPAL_CLIENT_ID']}:#{ENV['PAYPAL_SECRET_ID']}")
   }
body = {
  grant_type: 'client_credentials'
}
parameters = {
  'response_type' => 'token id_token',
}
# Esegui la richiesta POST per ottenere l'access token
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
request = Net::HTTP::Post.new(url.path+"?"+ URI.encode_www_form(parameters), headers)
request.set_form_data(body)
response = http.request(request)

# Controlla se la richiesta ha avuto successo e ottieni l'access token
if response.code == '200'
  
  access_token = JSON.parse(response.body)['access_token']
  session[:access_token]=access_token
  puts JSON.parse(response.body)
  # Usa l'access token per le tue richieste successive
else
  # Gestisci l'errore in caso di fallimento della richiesta
  puts "Errore nella richiesta di accesso: #{response.code} - #{response.body}"
end
uri = URI('https://api-m.sandbox.paypal.com/v2/checkout/orders')
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true

request = Net::HTTP::Post.new(uri.path)
request['Content-Type'] = 'application/json'

request['Authorization'] = "Bearer #{access_token}"
price = 10

payload = {
  intent: 'CAPTURE',
  purchase_units: [
    {
      
      amount: {
        currency_code: 'EUR',
        value: price
      }
    }
  ],
  payment_source: {
    paypal: {
      experience_context: {
        payment_method_preference: 'IMMEDIATE_PAYMENT_REQUIRED',
        payment_method_selected: 'PAYPAL',
        landing_page: 'LOGIN',
        user_action: 'PAY_NOW',
        return_url:  "https://loved-pangolin-hip.ngrok-free.app/users/"+(current_user.id).to_s+"/capture_order",
        cancel_url: "https://loved-pangolin-hip.ngrok-free.app/users/"+(current_user.id).to_s+"/cancel_order"

      }
    }
  }
}

request.body = payload.to_json
response = http.request(request)
puts response.body
links=JSON.parse(response.body)['links']
approve_premium_url=nil
links.each do |link|
  if link['rel'] == 'payer-action'
    approve_premium_url = link['href']
    break
  end
end
puts approve_premium_url
if JSON.parse(response.body)["status"]=="PAYER_ACTION_REQUIRED"
  session[:approve_premium_url] = approve_premium_url
  redirect_to user_path(id: current_user.id)
else
  flash[:error]="Errore nel pagamento"
  session[:approve__premium_url] = nil
  redirect_to  user_path(id: current_user.id)
end
end

def capture_order
    token=params[:token]
    id=params[:PayerID]
    puts id 
    puts token
    capture_url = "https://api-m.sandbox.paypal.com/v2/checkout/orders/#{token}/capture"
    capture_uri = URI.parse(capture_url)
    capture_http = Net::HTTP.new(capture_uri.host, capture_uri.port)
    capture_http.use_ssl = true

    capture_request = Net::HTTP::Post.new(capture_uri.path)
    capture_request['Content-Type'] = 'application/json'
    capture_request['Authorization'] = "Bearer #{session[:access_token]}"
    capture_response = capture_http.request(capture_request)
    puts "Questo è #{capture_response.body}"
    data = JSON.parse(capture_response.body)
    status = data["status"]

if status == "COMPLETED"
  @user=User.find(current_user.id)
  @user.update(role: "organizer")
  if @user.valid?
  flash[:success]="Il pagamento è stato completato con successo!"
  session[:approve_premium_url] = nil
  redirect_to user_path(id: current_user.id)
  
  else
  flash[:error]="Errore nel pagamento"
  session[:approve_premium_url] = nil
  redirect_to user_path(id: current_user.id)
  end
else
  flash[:error]="Errore nel pagamento"
  session[:approve_premium_url] = nil
  redirect_to user_path(id: current_user.id)
end
session[:approve_premium_url] = nil
   
end

def cancel_order
  flash[:error]="Hai rifiutato il pagamento"
  session[:approve_premium_url] = nil
  redirect_to user_path(id: current_user.id)
end  

  def destroy
  end

  def save_coordinates
     @user=User.find(current_user.id)
    if @user.update(latitude:params[:latitude]) &&  @user.update(longitude: params[:longitude])
     respond_to do |format|
      format.json { render json: { message: "Dati salvati correttamente", redirect_url: events_path}, status: :created}
      end
    else
      respond_to do |format|
        format.json { render json: { message: "Dati errati"}, status: :unprocessable_entity}
    end
  end
  end
end

app/views/users/index.html.erb
<table class="table table-striped table-sm table-responsive">
<div class="close-button"><%= link_to event_path(id: params[:id]) do %>
<i class="fa-solid fa-x " style="color: #8a8c8f;"></i>
 <% end %></div>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Numero Prevendite</th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
    <tr>
        <th scope="row"></th>
        <td><%= link_to user.username, user_path(id: user.id,)  %></td>
        <td><%=user.email %></td>
        <td><%= @presales.where(user_id: user.id).count%></td>
    </tr>
      <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% if session[:approve_premium_url]!=nil %>
  <p>Sto reindirizzando a <%= session[:approve_premium_url] %>...</p>
  <script>
    window.location.href = '<%= session[:approve_premium_url] %>'; // Reindirizza l'utente all'URL di approvazione
  </script>
<%else%>
<head>
  <style>
.button-container {
  display: flex;
  justify-content: center; /* Per centrare orizzontalmente */
  align-items: center; /* Per centrare verticalmente */
}

  .custom-link {
  margin-right: 10px;
  display: flex;
  justify-content: center;
  align-items: center;
  height:48px;
  background-color: #ff9900;
  color: white;
  border: none;
  border-radius: calc(4px + 20 * (100vw - 500px) / 5500);
  border: none;
  cursor: pointer;
  font-family: "Playfair Display";
  color: #fff;
  transition: background-color 0.3s, color 0.3s;
  transition: background-color 0.3s ease-in-out;
  width: calc(100px + 30 * (100vw - 500px) / 4000);
  text-decoration: none;
  text-align: center;
}

.custom-link:hover {
  background-color: #e68a00;
  text-decoration: none; / Rimuovi la sottolineatura anche durante il passaggio del mouse */
}
          .nButton-style {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #ff9900;
    color: white;
    border: none;
    border-radius: calc(4px + 20 * (100vw - 500px) / 5500);
    border: none;
    cursor: pointer;
    font-family: "Playfair Display";
    color: #fff;
    transition: background-color 0.3s, color 0.3s;
    transition: background-color 0.3s ease-in-out;
    width: calc(100px + 30 * (100vw - 500px) / 4000);
  }
  
  .nButton-style:hover {
    background-color: #e68a00;
  }
   body{
    height:100vh;

  }
  .custom-text {
  font-size: 20px; /* Puoi cambiare questo valore alla dimensione desiderata */
  color: white;
}
  .show-myCard{
    
    background-color: rgb(0,0,0);
     width: calc(800px + 22 * ((100vw - 500px) / (500*7)));
    height:auto;
     transform: translateY(-50px);
     display: flex;
justify-content: center;
align-items: center;
     }
  .custom-label {
    color: rgb(156, 131, 185);
    font-family: "Exo 2", sans-serif;
    font-size:100;
  }
  </style>
</head>
<body>
<header class="show-header">
<%= image_tag("logo.png",class: "img-responsive")%>
</header> 
<div class="form-container show-container">
      <div class="show-myCard">
<label for="username" class="custom-label" style="font-size: 25px !important;">Username:</label>
<span class="custom-text" id="username"><%= @user.username %></span>
<br>
<label for="ruolo" class="custom-label"  style="font-size: 25px !important;" >Ruolo:</label>
<span class="custom-text" id="ruolo"><%= @user.role %></span>
<br>
<label for="email" class="custom-label"  style="font-size: 25px !important;">Email:</label>
<span class="custom-text" id="email"><%= @user.email %></span>
<br>

<div class="button-container">
  <% if params[:id].to_i == current_user.id %>
    <%= link_to "Gestisci account", edit_user_registration_path, class: "custom-link" %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "custom-link", id: "logout-button" %>
    <% if Event.where(organizer_id: params[:id], status: "draft").any? %>
      <%= link_to "Bozze", events_path(status: "draft"), class: "custom-link" %>
    <% end %>
    <% if can?(:create_order, User) && !can?(:manage, :all) %>
  <%= link_to "Acquista Premium", premium_path(user_id: current_user.id), class: "custom-link",id:"acquista-premium-link" %>

    <% end %>
  <% end %>
  <% if Presale.where(user_id: params[:id]).any? %>
    <%= link_to "Eventi Acquistati", events_path(user_id: params[:id], commit: "presale"), class: "custom-link" %>
  <% end %>
  <% if can?(:ban, User) %>
    <% if params[:id].to_i != current_user.id %>
      <% if User.find(params[:id]).role == "organizer" %>
        <%= link_to "Revoca privilegi", edit_user_path(commit: "Revoca", id: params[:id].to_i), class: "custom-link" %>
      <% end %>
      <% if Ban.where(user_id: params[:id]).exists? %>
        <%= link_to "Sbanna Utente", user_ban_path(user_id: params[:id], id: Ban.find_by(user_id: params[:id]).id), method: :delete, class: "custom-link" %>
      <% else %>
        <%= link_to "Banna Utente", new_user_ban_path(user_id: params[:id]), method: :get, class: "custom-link" %>
      <% end %>
    <% end %>
  <% end %>
  <% if Event.where(status: "published", organizer_id: params[:id]).any? %>
    <%= link_to "Eventi Organizzati", events_path(commit: "organized", organizer_id: params[:id]), class: "custom-link" %>
  <% end %>
</div>



 </div>
<nav class="navbar fixed-bottom navbar-light d-flex justify-content-center align-items-center">

  <!-- Icona "Home" -->
 
<nav class="navbar navbar-inferiore fixed-bottom navbar-light d-flex justify-content-center align-items-center">

  <!-- Icona "Home" -->
  <ul><li><%= link_to events_path do %>
    <i class="fas fa-home fa-2x" ></i>
<% end %></li>

  <!-- Icona "Aggiungi" -->
  <% if can?(:create, Event)%>
  <li>
  <%= link_to new_event_path do %>
    <i class="fas fa-plus fa-2x" id="crea-evento-button"></i>
<% end %></li>
<%end%>
<!-- Icona "Salva" -->
<li>
<%= link_to user_saves_path(user_id: current_user.id),data: { turbo: false } do %> <!-- ho messo data per disabilitare le proprietà di turbolink e ricaricare la pagina -->
    <i class="fas fa-heart fa-2x"></i>
  
  <%end%></li>
 <!-- Icona "Utente" -->
 <li>
<%= link_to user_path(current_user) do %>
    <i class="fas fa-user fa-2x" ></i>
<% end %> </li>
</ul>
</nav>
<%end%>