config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  
  
  resources :users do
    resources :saves
    resources :presales
    resources :bans
  end
  resources :events  do
      resources :evaluations

      
  end
  root to: 'events#index'
  post "/events", to: "events#create",as: "create_event"
  delete "/users/:user_id/:event_id/saves", to: "saves#destroy",as: "delete_saves"
  post "/events/:event" ,to: "events#create",as: "draft_event"
  post "events/:event_id/create_order", to: "presales#create_order",as: "create_order"
  get "events/:event_id/presales/capture_order", to: "presales#capture_order"
  get "events/:event_id/presales/cancel_order", to: "presales#cancel_order"
  get "events/:event_id/presales",to: "presales#index",as: "all_presales"
  get "events/:role",to: "events#index",as: "index_events"
  get "users/:user_id/create_order",to: "users#create_order",as: "premium"
  get "users/:user_id/capture_order",to: "users#capture_order"
  get "users/:user_id/cancel_order",to: "users#cancel_order"
  get "users/:user_id/geolocation", to: "users#geolocation"
  post "/users/save_coordinates", to: "users#save_coordinates"

  post "/events/:event_id/evaluations/:star_radio", to: "evaluations#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_icon.htlm.erb
<div id="footer" >


  
 

  <!-- Icona "Home" -->
  <%= link_to events_path do %>
  <a href="<%= events_path%>">
    <i class="fas fa-home fa-2x"></i>
  </a>
<% end %>
<% if  current_user.role=="organizer" || current_user.role=="admin" %>
<%= link_to new_event_path do %>
  <!-- Icona "Home" -->
  <a href="<%= new_event_path %>">
    <i class="fas fa-plus fa-2x"></i>
  </a>
<% end %>
<% else %>
<%= link_to new_event_path do %>
  <!-- Icona "Home" -->
  <a href="">
    <i class="fas fa-plus fa-2x disabled"  ></i>
  </a>
<% end %>
<% end%>

<!-- Icona "Salva" -->
<%= link_to user_saves_path(user_id: current_user.id) do %>
  <!-- Icona "Home" -->
  <a href="<%= user_saves_path(user_id: current_user.id) %>">
    <i class="fas fa-save fa-2x"></i>
  </a>

<% end %> 
<!-- Icona "Profilo" -->
 <i class="fas fa-user fa-2x"></i>
	
	  </div>