config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  
  
  
  resources :users do
    resources :saves
    resources :presales
    resources :bans
  end
  resources :events  do
      resources :evaluations

      
  end
  root to: 'events#index'
  post "/events", to: "events#create",as: "create_event"
  delete "/users/:user_id/:event_id/saves", to: "saves#destroy",as: "delete_saves"
  post "/events/:event" ,to: "events#create",as: "draft_event"
  post "events/:event_id/create_order", to: "presales#create_order",as: "create_order"
  get "events/:event_id/presales/capture_order", to: "presales#capture_order"
  get "events/:event_id/presales/cancel_order", to: "presales#cancel_order"
  get "events/:event_id/presales",to: "presales#index",as: "all_presales"
  get "events/:role",to: "events#index",as: "index_events"
  get "users/:user_id/create_order",to: "users#create_order",as: "premium"
  get "users/:user_id/capture_order",to: "users#capture_order"
  get "users/:user_id/cancel_order",to: "users#cancel_order"
  get "users/:user_id/geolocation", to: "users#geolocation"
  post "/users/save_coordinates", to: "users#save_coordinates"

  post "/events/:event_id/evaluations/:star_radio", to: "evaluations#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :saves,dependent: :destroy,class_name: "Save"
    has_many :presales,dependent: :destroy
    has_many :evaluations,dependent: :destroy
    belongs_to :user,foreign_key: :organizer_id
    has_many :clients, :through => :presales,:source => :user
    has_many :evaluators, :through => :evaluations,:source => :user
    validates :price,:date,:location,presence:true, if: :published? #prezzo,titolo,data,location attributi not null
    validates :title,presence: :true
    validates_uniqueness_of :title,scope: :status,if: :published?
    validates :organizer_id,presence:true
    validate :organizer
    validate :Presales_init
    validate :AvgValue
    validate :date_cannot_be_in_the_past
    validate :max_length
    validate :print_errors

    enum status: { draft: 'draft', published: 'published' }

    def max_length
        if self.description.present? &&  self.description.length > 200
            puts self.description.length
            errors.add("Descrizione", "deve essere lunga al massimo 200 caratteri")
        end
    end
        

    def published?
        status == 'published'
      end

      def draft?
        status == 'draft'
      end

    def Presales_init
        if self.limit.nil?
            self.limit=100
            self.presales_left = 100  
        else
            self.presales_left = self.limit

        end
    end

    def date_cannot_be_in_the_past
        if date.present? && date <= Date.today
          errors.add("Data", "deve essere maggiore della data odierna")
        end
    end

    def AvgValue
        self.avgvalue ||= 0.0
    end

    def print_errors
        errors.full_messages.each do |message|
          puts message
        end
    end
    
    def saved_by?(user)
        Save.exists?(user_id: user.id,event_id: id)
    end

    def self.filter(filter_criteria)
        # Logica di filtraggio basata sui criteri passati come parametro.
        # Esempio di implementazione:
        filtered_events = all

        if filter_criteria[:location].present?
            # Filtro per la località solo se è stata specificata nei criteri di ricerca
            filtered_events = filtered_events.where(location: filter_criteria[:location])
          end
    
        if filter_criteria[:avgvalue_min].present?
            filtered_events = filtered_events.where('avgvalue >=', filter_criteria[:avgvalue_min])
        end
    
        if filter_criteria[:price_min].present?
            filtered_events = filtered_events.where('price >= ?', filter_criteria[:price_min])
        end
    
        if filter_criteria[:price_max].present?
            filtered_events = filtered_events.where('price <= ?', filter_criteria[:price_max])
        end
    
        filtered_events
      end

    def organizer
        organizer = User.find_by(id: organizer_id, role: "admin") || User.find_by(id: organizer_id, role: "organizer")
        if organizer.nil?
            errors.add(:base, "deve corrispondere a un utente con ruolo 'organizer' o 'admin'") 
            
        end
      end
    
      

    

end

app/controllers/events_controller.rb
require 'net/http'

class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    session[:approve_premium_url]=nil 
    session[:approve_url]=nil 
    if params[:status]=="draft"
      @events=Event.where(status:"draft",organizer_id: current_user.id)
      return
    elsif params[:commit]=="organized"
      @events=Event.where(status: "published", organizer_id: params[:organizer_id])
      return
    elsif params[:commit]=="presale"
      
      @events = Event.joins(:presales).where(presales: { user_id: params[:user_id] }).distinct
      return

    else
      @events = Event.where(status: "published")
      if params[:search].present?
        @events = @events.where("location LIKE ?", "%#{params[:search]}%")
      end
    end
    if params[:minPrice].present?
      @events = @events.where('price >= ?', params[:minPrice])
    end
    if params[:maxPrice].present?
      @events = @events.where('price <= ?', params[:maxPrice])
    end
    if params[:minDate].present?
      @events = @events.where('date >= ?', params[:minDate])
    end
    if params[:maxDate].present?
      @events = @events.where('date <= ?', params[:maxDate])
    end
    if params[:sort_by] == "price"
      @events = @events.order(price: :asc)
    elsif params[:sort_by] == "avgvalue"
      @events = @events.order(avgvalue: :desc)
    elsif params[:sort_by] == "date"
       @events = @events.order(date: :asc)
    elsif params[:sort_by] == "distance"
      #uso l'Api di google maps
      if current_user.latitude==nil || current_user.longitude==nil
        flash[:error]="Attiva geolocalizzazione"
        redirect_to events_path
        return
      end
      current_latitude = current_user.latitude
      current_longitude = current_user.longitude
      @events.each do |event|
        city_name = event.location  # Nome della città di cui vuoi ottenere le coordinate
        api_key = 'AIzaSyDhE8iSfvpzBIi_oOpbnbWNNolFN5W3EtI'  # Sostituisci con la tua chiave API
        url = "https://maps.googleapis.com/maps/api/geocode/json"
        params = {
          address: city_name,
          key: api_key
        }
        
        response = HTTParty.get(url, query: params)
        data = JSON.parse(response.body)
        
        if data['status'] == 'OK'
          location = data['results'][0]['geometry']['location']
          latitude = location['lat']
          longitude = location['lng']
          puts "Coordinate di #{city_name}: Latitudine #{latitude}, Longitudine #{longitude}"
          distance =  (6371*(Math::PI)*Math.sqrt((current_latitude-latitude)*(current_latitude-latitude) + Math.cos(current_latitude/57.29578)*Math.cos(latitude/57.29578)*(current_longitude-longitude)*(current_longitude-longitude))/180); #funzione di heaviside per calcolare la distanza
          puts "la distanza è #{distance}"
          event.update(distance: distance)
        else
          flash[:error]= "Errore nella richiesta di geocoding"
        end
        
      end
      @events = @events.order(distance: :asc)
    else
      # Ordine predefinito (per esempio, per avgvalue più alto)
      @events = @events.order(avgvalue: :desc)
    end
    @events = @events.where("date > ?", Date.today)
  end

  def show
    @is_event_background=true  #aggiungo sfondo background
    @event=Event.find(params[:id])
    respond_to do |format|
      format.html { render :show}
      format.json { render :show, status: :created, location: @event }
    end
  end

  def new
    @is_event_background=true  #aggiungo sfondo background
    @event=Event.new
  end

  def create
    
    # Voglio che quando clicco su "Salva bozza" la verifica di presenza sia solo su "date" e "title"
    @event = Event.new(event_params.merge(organizer_id: current_user.id))
    flash[:title]=params[:event][:title]
    flash[:date]=params[:event][:date]
    flash[:price]=params[:event][:price]
    flash[:location]=params[:event][:location]
    flash[:description]=params[:event][:description]
    flash[:limit]=params[:event][:limit]

    if params[:commit] == 'Bozza' #sto salvando come bozza
      @event.status = 'draft'
      if @event.save
        redirect_to @event, notice: 'Bozza salvata con successo.'
      else
        flash[:error]=@event.errors.full_messages.join(",")
        redirect_to new_event_path
      end
    elsif params[:commit] == 'Pubblica'#sto pubblicando di un evento
      @event.status = 'published'
      if params[:organizer]
        @event.organizer_id = params[:organizer]
      end
      if @event.valid?
        if @event.save
          flash[:success] = 'L\'evento è stato creato con successo!'
          redirect_to events_path
        else
          flash[:error] = @event.errors.full_messages.join(", ")
          redirect_to new_event_path
        end
      else
        flash[:error] = @event.errors.full_messages.join(", ")
        redirect_to new_event_path
      end
    elsif params[:commit] == 'Pubblica Bozza'# sto pubblicando una bozza
      @event.status = 'published'
      if @event.valid?
        if @event.save
          flash[:success] = 'L\'evento è stato creato con successo!'
          respond_to do |format|
          format.json { render json: { message: "Evento creato correttamente", redirect_url: event_path(id: @event.id)}, status: :created}
          end
        else
          flash[:error] = @event.errors.full_messages.join(", ")
          respond_to do |format|
          format.json do
            render json: { error: "Errore nella creazione", redirect_url: edit_event_path(id: @event.id) }, status: :unprocessable_entity

          end
          end
        end
      
      else
        flash[:error] = @event.errors.full_messages.join(", ")
        respond_to do |format|
          format.json do
            render json: { error: "Errore nella creazione", redirect_url: edit_event_path(id: params[:id]) }, status: :unprocessable_entity

          end
        end
        
      end
      
    end

 
  end
  

  def edit
    @is_event_background=true   #aggiungo sfondo background

    @event=Event.find(params[:id])
    authorize! :edit, @event, :message => "BEWARE: you are not authorized to edit movies."
  end

  def update
    @event = Event.find(params[:id])
    flash[:title]=params[:event][:title]
    flash[:date]=params[:event][:date]
    flash[:price]=params[:event][:price]
    flash[:location]=params[:event][:location]
    flash[:description]=params[:event][:description]
    flash[:limit]=params[:event][:limit]
    if @event.update(event_params)
      flash[:success] = 'L\'evento è stato aggiornato con successo!'
      redirect_to event_path
    else
      # Errore nell'aggiornamento
      flash[:error]=@event.errors.full_messages.join(', ')
      redirect_to edit_event_path(@event)
    end
  end

  def destroy
    @event=Event.find(params[:id])
    status=@event.status
    if @event.destroy
      if status == "published"
      flash[:success] = 'L\'evento è stato eliminato con successo!'
      redirect_to events_path
      else
        flash[:success] = 'La bozza è stata eliminata con successo!'
        redirect_to events_path(status: "draft")
      end
    else
      flash[:error]=@event.errors.full_messages.join(', ')  
    end
  end
  def event_params
    params.require(:event).permit(:title, :date, :price, :location,:limit,:description)
  end

  
end
 

app/helpers/events_helper.rb
module EventsHelper    
end

app/views/events/new.html.erb
<!-- Voglio che ogni bozza abbia un titolo quindi bisogna fare un check nella new.htlm.erb per controllare se il titolo è stato inserito quando viene salvata la bozza-->

<head>
  <style>
   body{
    height:100vh;
  }  
  </style>
</head>
<body>

<header class="show-header">
		
<%= image_tag("logo.png",class: "img-responsive")%>
</header> 
  <div class="form-container show-container">
      <div class="show-myCard new-myCard">
       <%= form_with model: @event, url: create_event_path(@event), method: :post, id: "event-form" do |form| %>
        <label for="title" >Titolo: </label>

        <%= form.text_field :title, id: "title", name: "event[title]", title: "Title", class: "form-control", placeholder: "Inserisci il titolo",value: flash[:title] %>

       <label for="date">Data:</label>
       <%= form.date_field :date, id: "date", name: "event[date]", title: "Date", class: "form-control", placeholder: "Seleziona la data",value: flash[:date] %>

        <label for="price">Prezzo:</label>
        <%= form.number_field :price, id: "price", min: 0, step: 0.01, name: "event[price]", title: "Price", class: "form-control", placeholder: "Inserisci il prezzo",value: flash[:price] %>

        <label for="location">Luogo:</label>
        <%= form.text_field :location, id: "location", name: "event[location]", title: "Location",  class: "form-control",placeholder: "Inserisci la location",value: flash[:location] %>
        
        <label for="description">Descrizione:</label>
        <%= form.text_area :description,id: "description",name: "event[description]",title:"Description", rows: 1, class: "form-control", placeholder: "Inserisci la descrizione",value: flash[:description]%>
 
        <label for="limit">Limite partecipanti:</label>
        <%= form.number_field :limit, id: "limit", min: 1, name: "event[limit]", title: "Participant Limit", class: "form-control", placeholder: "Inserisci il limite partecipanti (opzionale)",value: flash[:limit] %>
        <div class="submit-group">
          <div class="publish-container">
              <div> <%= form.submit "Bozza", class: "save draft" %></div>
             <div><%= form.submit "Pubblica", class: "save success", id: "publish-button" %></div>
          </div>
          <div style="display:flex">
           <a  href="#"  class="save error" onclick="goBack()">Annulla</a>
          </div>
        </div>
      <% end %>
  </div>
</div>


<nav class="navbar navbar-inferiore fixed-bottom navbar-light d-flex justify-content-center align-items-center">

  <!-- Icona "Home" -->
  <ul><li><%= link_to events_path do %>
    <i class="fas fa-home fa-2x" ></i>
<% end %></li>

  <!-- Icona "Aggiungi" -->
  <% if can?(:create, Event)%>
  <li>
  <%= link_to new_event_path do %>
    <i class="fas fa-plus fa-2x"></i>
<% end %></li>
<%end%>
<!-- Icona "Salva" -->
<li>
<%= link_to user_saves_path(user_id: current_user.id),data: { turbo: false } do %> <!-- ho messo data per disabilitare le proprietà di turbolink e ricaricare la pagina -->
    <i class="fas fa-heart fa-2x"></i>
  
  <%end%></li>
 <!-- Icona "Utente" -->
 <li>
<%= link_to user_path(current_user) do %>
    <i class="fas fa-user fa-2x" ></i>
<% end %> </li>
</ul>
</nav>
</body>

app/views/events/show.html.erb
<style>
body{
  display:flex;
  flex-direction:column;
  align-items:center;
  height:100vh;
  width:100vw;
  overflow:scroll;
  
}
a{
  text-decoration:none;
}

</style>
<% if session[:approve_url]!=nil %>
  <p style="color:white">Sto reindirizzando a <%= session[:approve_url] %>...
  <script>
    window.location.href = '<%= session[:approve_url] %>'; // Reindirizza l'utente all'URL di approvazione per pagamento
  </script>

<% else %>  

<header class="show-header">
		
<%= image_tag("logo.png",class: "img-responsive")%>
</header> 
 
  <div class="show-container">
   <div class="events-show" >
      <div class="show-myCard"> 
        <div class="card-inner">
            <div class="card-front" id="<%= @event.id %>">
                  <div class="top-text"><div class="title"><%= @event.title %></div>
                  <div class="location"> <%= @event.location %>,Italia</div>
                  <div class="price">Prezzo: <%=@event.price %>&euro;</div>
                  <div class="date">
                  <% if @event.date ==nil%>
                   Da Inserire
                  <%else%> 
                  <%= @event.date %>
                  <%end%></div>
              </div>

                  <div class="circle"><%= image_tag("event.jpg")%></div>
                  <%if @event.status== "published"%>
                  <div class="star" style="position:absolute;top:5%;right:5%">
                  <% if @event.saved_by?(current_user) %>
                  <%= link_to delete_saves_path(user_id: current_user.id, event_id: @event.id), method: :delete do %>
                  <i class="fa-solid fa-heart fa-xl" style="color: #9c83b9;"></i> 
                  <% end %>
                  <% else %>
                  <%= link_to user_saves_path(user_id: current_user.id, event_id: @event.id), method: :post do %>
                  <i class="fa-regular fa-heart fa-xl" style="color: #9c83b9;"></i>
                  <% end %>
                  <% end %>
                  </div>
                  <%end%>
                  <div class="card-body">
                  <% if @event.title == "Piper Roma"%>
                  <%= image_tag("Piper.jpg",class: "card-img custom-image")%>
                  <% elsif @event.title == "Nice Disco"%>
                  <%= image_tag("Nice.jpg",class: "card-img custom-image")%> 
                  <% elsif @event.title == "FestivalRimini2024"%>
                  <%= image_tag("Rimini.jpg",class: "card-img custom-image")%>
                  <% elsif @event.title == "Cocoricò"%>
                  <%= image_tag("Cocorico",class: "card-img custom-image")%>
                  <% elsif @event.title == "Space Elettronic"%>
                  <%= image_tag("Space-Elettronic.png",class: "card-img custom-image")%>
                  <%else%>
                  <%= image_tag("event.jpg",class: "card-img custom-image")%>
                  <%end%> </div>   

                  <div class="card-footer">
                <%= @event.avgvalue %>/5
                <i class="fa-solid fa-star" style="color: rgb(255,215,0);"></i></div> 
                  
                </div>
            <div class="card-back">
                <p class="organizer"> <%if User.find(@event.organizer_id).username!=nil %>
                <%= link_to User.find(@event.organizer_id).username, user_path(User.find(@event.organizer_id)) %>
                <%end%>presenta <%= @event.title%></p>
                <p class="description"><%=@event.description%></p>
                
                <% if can?(:manage,:all)%>
                 <% if @event.status == "published"%>
                   <% if Presale.all.where(event_id: @event.id).any?%>
                <p class="buyers"><%= link_to "Lista Acquirenti", users_path(id: @event.id)%></p>
                <%end%>
                <%end%>
                <%end%>
                <% if @event.status=="published"%>
                <p class="presales">Prevendite Rimaste: <%= (@event.presales_left)-(Presale.where(event_id:@event.id).count) %></p>
                <%end%>
             </div>
         </div>
      </div>
      <div class="buttons-group" style="width:100%">

<% if(@event.organizer_id==current_user.id && can?(:create, Event) )||  (can?(:manage, :all) && @event.status == "published")%>
<%= link_to "Elimina",event_path(id: @event.id),method: :delete, class: "btn btn-danger"%> <!-- metodo base per riferirsi alla destroy altrimenti si hanno problemi -->
<%= link_to "Modifica",edit_event_path,data: { turbo: false }, class: "btn btn-success" %>
<%end%>

<% if @event.status=="published"%>
<% if !Evaluation.exists?(event_id: @event.id, user_id: current_user.id)%>
<%if params[:commit]!=nil  && Date.today>@event.date%>
<a class= "btn btn-warning valuta" data-bs-toggle="modal" data-bs-target='#staticBackdrop'>Valuta</a>
<%end%>
<%end%>
<%if params[:commit]!="organised" && Date.today < @event.date%>
<%= link_to create_order_path(event_id: params[:id]),method: :post, class: "premium-button" do%>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 24">
        <path d="m18 0 8 12 10-8-4 20H4L0 4l10 8 8-12z"></path>
    </svg>
    Acquista
<%end%>
<%end%>
<%end%>
</div>
  </div>
  <%= link_to events_path(commit: params[:commit],user_id: params[:organizer_id] || params[:user_id]),class:"back" do%>

  <svg height="16" width="16" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1024 1024">
  <path d="M874.690416 495.52477c0 11.2973-9.168824 20.466124-20.466124 20.466124l-604.773963 0
   188.083679 188.083679c7.992021 7.992021 7.992021 20.947078 0 28.939099-4.001127 3.990894-9.240455 
   5.996574-14.46955 5.996574-5.239328 0-10.478655-1.995447-14.479783-5.996574l-223.00912-223.00912c-3.837398-3.837398-5.996574-9.046027-5.996574-14.46955 0-5.433756 2.159176-10.632151 5.996574-14.46955l223.019353-223.029586c7.992021-7.992021 20.957311-7.992021
    28.949332 0 7.992021 8.002254 7.992021 20.957311 0 28.949332l-188.073446 188.073446 604.753497 0C865.521592 475.058646 
    874.690416 484.217237 874.690416 495.52477z"></path></svg>
Back
<%end%>


<nav class="navbar navbar-inferiore fixed-bottom navbar-light d-flex justify-content-center align-items-center">

  <!-- Icona "Home" -->
  <ul><li><%= link_to events_path do %>
    <i class="fas fa-home fa-2x" ></i>
<% end %></li>

  <!-- Icona "Aggiungi" -->
  <% if can?(:create, Event)%>
  <li>
  <%= link_to new_event_path do %>
    <i class="fas fa-plus fa-2x"></i>
<% end %></li>
<%end%>
<!-- Icona "Salva" -->
<li>
<%= link_to user_saves_path(user_id: current_user.id),data: { turbo: false } do %> 
    <i class="fas fa-heart fa-2x"></i>
  
  <%end%></li>
 <!-- Icona "Utente" -->
 <li>
<%= link_to user_path(current_user) do %>
    <i class="fas fa-user fa-2x" ></i>
<% end %> </li>
</ul>
</nav>
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Valuta l'evento con un voto da 1 a 5</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" style="display:flex; justify-content:center">
    
<%= form_tag(event_evaluation_path(event_id: @event.id), method: 'post') do %>
  <div class="rating">
<%= radio_button_tag 'star_radio',5,false,id: "star-5"%>
    <%= label_tag 'star-5' do %>
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path>
      </svg>
    <% end %>
<%= radio_button_tag 'star_radio',4,false,id: "star-4"%>
    <%= label_tag 'star-4' do %>
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path>
      </svg>
    <% end %>

    <%= radio_button_tag 'star_radio',3,  false, id: 'star-3' %>
    <%= label_tag 'star-3' do %>
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path>
      </svg>
    <% end %>

    <%= radio_button_tag 'star_radio',2,  false, id: 'star-2'%>
    <%= label_tag 'star-2' do %>
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path>
      </svg>
    <% end %>

    <%= radio_button_tag 'star_radio',1, false, id: 'star-1' %>
    <%= label_tag 'star-1' do %>
      <svg viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path>
      </svg>
    <% end %>

  </div>

  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
         <%= submit_tag 'Invia' , class: "btn btn-primary",id: @event.id  %>

      </div>
      <% end %>

    </div>
  </div>
</div>
<%end%>